### ISSUE TITLE
[NF] Add UZS (Uzbek Sum) currency

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#450]
**Is your feature request related to a problem? Please describe.**
I live in Uzbekistan and I want to add an account with UZS currency

**Describe the solution you'd like**
I need the UZS (Uzbek Sum) currency

**Describe alternatives you've considered**
Use other currency with editing conversion rate

**Comment by lyskouski** [comment]
Hello, thanks for your request.

Do you have a special symbol for the currency?

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov ,
The error is fixed, distribution would take at max 72 hours.

Would appreciate your help in checking the localization:
https://github.com/lyskouski/app-finance/tree/main/assets/l10n/help_metrics_account_uz.md
https://github.com/lyskouski/app-finance/tree/main/assets/l10n/help_metrics_bill_uz.md
https://github.com/lyskouski/app-finance/tree/main/assets/l10n/help_metrics_budget_uz.md
https://github.com/lyskouski/app-finance/tree/main/assets/l10n/privacy_policy_uz.md
https://github.com/lyskouski/app-finance/tree/main/assets/l10n/terms_of_use_uz.md
https://github.com/lyskouski/app-finance/tree/main/lib/l10n/app_uz.arb

[localization_e7aaf5c86ef951e267fda30caeff76921f747862.csv](https://github.com/lyskouski/app-finance/files/13756481/localization_e7aaf5c86ef951e267fda30caeff76921f747862.csv)

Kind regards,
Viachaslau

**Comment by muhammadyusuf-kurbonov** [comment]
Assalamu alaykum.

UZS haven't yet its special symbol. And of course I can and will check translations later. 

Thank you

**Comment by lyskouski** [comment]
Greatly appreciate that. Whenever you'll find anything, don't hesitate to create a new issue.

![image](https://github.com/lyskouski/app-finance/assets/8281925/bcfec6d9-3bb4-43b8-8f0f-9f444aa6f028)
