### ISSUE TITLE
[BF] Linux Flatpak Version: app is not saving data

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#452]
**Describe the bug**
Running App in Linux via Flatpak. After restarting the app all data is lost.

**To Reproduce**
1. Go to Accounts and add an account (or any other action)
2. Click on `x` in right top corner (or press Alt + F4)
3. Restart the app

**Expected behavior**
Data should be persistent.

**Screenshots**
![image](https://github.com/lyskouski/app-finance/assets/45625440/482645fd-42fb-4173-b948-9fa95311f814)
after restart
![image](https://github.com/lyskouski/app-finance/assets/45625440/33f674b2-3f21-426e-97e7-cc0a65e89c02)

**Desktop (please complete the following information):**
 - OS: Fedora (Linux 6.6.7) + Flatpak 1.15.6
 - Browser Chrome
 - Version 39

**Additional context**

**Comment by muhammadyusuf-kurbonov** [comment]
https://github.com/lyskouski/app-finance/blob/773444bf1eb65924062d228ff248e9f2c1227160/lib/_classes/storage/transaction_log.dart#L54C1-L59C6

It seems it is using `/tmp` directory. In Flatpaks `tmp` is not persistent. I haven't tested it yet, so it is only a guess

**Comment by muhammadyusuf-kurbonov** [comment]
Created a PR with patch for flatpak manifest. App need a permission to access `Documents` folder

**Comment by lyskouski** [comment]
Hello @muhammadyusuf-kurbonov,
Thanks for identifying the problem. Will check the state https://github.com/flathub/com.tercad.fingrom/pull/13

**Comment by lyskouski** [comment]
The change is not helping, it looks like per each session a new temporal folder is generated.

```dart
// lib/_classes/storage/transaction_log.dart
    try {
      final dir = await getApplicationDocumentsDirectory();
      file = await _get(dir);
    } catch (e) {
      file = await _get(Directory.systemTemp);
    }
```

**Comment by muhammadyusuf-kurbonov** [comment]
Yes. It is. And I have granted access to xdg-documents. It helped. Maybe I edit manifest wrong?

**Comment by muhammadyusuf-kurbonov** [comment]
Now I can find app-finance.log file in Documents/.terCAD directory (it is encrypted or encoded..)

**Comment by lyskouski** [comment]
Great if it works on your side. _Assume, there may be some misconfiguration from mine._
Will release it on Flathub then.

**Comment by lyskouski** [comment]
Hello @muhammadyusuf-kurbonov ,
`- --filesystem=xdg-documents/.terCAD:create` has helped to resolve the issue from my side.
Will release 5.2.6 shortly

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov ,
I've updated flathub - https://buildbot.flathub.org/#/builders/2/builds/43094, please, check 5.2.6 version if it works from your side as well. Thanks in advance
