### ISSUE TITLE
[BF] Wrong Color for Button on "Create new Transaction"-page

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#465]
**Describe the bug**
`Add new *` button in bottom part of `Create new Transaction` page has wrong color

**To Reproduce**
1. Go to Home
2. Click on FAB in the right bottom corner (Add Bill, Income or Transfer)
3. Bottom button is too big and has wrong content color

**Expected behavior**
Readable content color

**Screenshots**
![image](https://github.com/lyskouski/app-finance/assets/45625440/e19da395-a9f0-4358-84c0-7093bf229a65)
![image](https://github.com/lyskouski/app-finance/assets/45625440/18dc9802-d0b7-45f1-bea8-4d97ff79304d)

**Desktop (please complete the following information):**
 - OS: Fedora 39 Linux 6.6.13
 - Runtime: Flatpak 1.15.6
 - Version 5.3.2
 - Build: 1542

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov, thanks for highlighting the problem.

**Comment by lyskouski** [comment]
![image](https://github.com/lyskouski/app-finance/assets/8281925/8c4415c4-9fb1-4280-9bf8-d20f8dd14a8c)
![image](https://github.com/lyskouski/app-finance/assets/8281925/c10b351b-0f8b-4c9b-9680-cd9b31b25c77)

**Comment by lyskouski** [comment]
Released

**Comment by muhammadyusuf-kurbonov** [comment]
Thank you
