### ISSUE TITLE
[BF] Delete transaction doesn't remove transaction from list

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#466]
**Describe the bug**
Delete transaction doesn't remove it from the transactions list of accounts. 

**To Reproduce**
1. Go to Accounts page
2. Click on any account with transactions
3. Click on any transaction
4. Click on Delete button on right corner
5. Confirm delete
6. See error

**Expected behavior**
Balance is reduced correctly, but the transaction is not hidden from the list, suggested making it semitransparent, and disabling clicking. Because I can delete it again and my account balance is negative now.

**Screenshots**
![image](https://github.com/lyskouski/app-finance/assets/45625440/30599429-e54c-4c2e-b793-035873d11ce7)

**Desktop (please complete the following information):**
 - OS: Fedora 39, Linux 6.6.13
 - Runtime: Flatpak v1.15.6
 - Version 5.3.2
 - Build: 1542

**Additional context**

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov, that for identifying the issue.

**Comment by lyskouski** [comment]
Released

**Comment by muhammadyusuf-kurbonov** [comment]
Thanks
