### ISSUE TITLE
[CI] Transactions aren't saving

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#469]
**Describe the bug**
After restarting the app transactions aren't been saved.  The accounts are. 

**To Reproduce**
1. Go to Home page
2. Click on Add Income, Bill, Transfer
3. Add a new transaction. Does not matter which type
4. Account balance is changed, transaction is in list
5. Close the app
6. Start Fingrom again
7. No transactions, accounts' balances are 0

**Expected behavior**
All transactions are reloaded and saved. Accounts balances are correct

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39, Linux 6.6.13
 - Runtime: Flatpak v1.15.6
 - Version 5.3.4
 - Build: 1551

**Additional context**

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov,

- May it be that currency is not set?
- Is it possible to share `app-finance.log` from `.terCAD` folder (in Documents or Home)?

Thanks in advance

**Comment by lyskouski** [comment]
I've found one possible issue, since Uzbek currency has zero decimals. Will release it shortly, please, check.

**Comment by lyskouski** [comment]
P.S. All missings should be recovered.

**Comment by lyskouski** [comment]
Dear @muhammadyusuf-kurbonov,
Please, check released v5.3.5 version. Theoretically it should resolve the restoring process (at start).

**Comment by muhammadyusuf-kurbonov** [comment]
Got it. I had this issue also with USD currency. I will check it later. Thank you very much

**Comment by muhammadyusuf-kurbonov** [comment]
[app-finance.log](https://github.com/lyskouski/app-finance/files/14152568/app-finance.log)
Log file

**Comment by lyskouski** [comment]
Hello @muhammadyusuf-kurbonov,
Thanks for providing the log (it can be deleted if needed), the issue was relevant to "icon"-property. Fixed in v5.3.6 (in a way to release). One account and three invoices are in place, will be restored after the upgrade.

_As a note, Invoices are not shown in Bills tab, but can be viewed from Details for the Account itself. Also, it's possible to add grid with Invoices to the main page by using "Customize Page" (button) to configure own view (https://youtu.be/sNTbpILLsOw?si=cDaFIOvd1fkpxQ1U&t=106)._

**Comment by muhammadyusuf-kurbonov** [comment]
Invoices are showing in Invoices section. 
![image](https://github.com/lyskouski/app-finance/assets/45625440/97d44ee2-a5e5-4fb2-9251-5cc96ad64571)
But no account balance updated.

**Comment by lyskouski** [comment]
Hello @muhammadyusuf-kurbonov, 
Was it done with 5.3.6 ?

![image](https://github.com/lyskouski/app-finance/assets/8281925/9fc2715f-15ce-4ffd-8546-d5f06ab63b9a)
![image](https://github.com/lyskouski/app-finance/assets/8281925/b77d9c34-f8a9-4d83-8a50-cd15864ca9d5)

**Comment by lyskouski** [comment]
Thanks, @muhammadyusuf-kurbonov, one more issue with doubled recovery

![image](https://github.com/lyskouski/app-finance/assets/8281925/d20aef88-aac6-4388-9efc-277640f57320)

**Comment by lyskouski** [comment]
Added "Remove existing data" for the clean restore procedure.

![image](https://github.com/lyskouski/app-finance/assets/8281925/57d617da-d816-4a4a-9f14-592898e1228d)

**Comment by lyskouski** [comment]
Released in 5.3.7

**Comment by muhammadyusuf-kurbonov** [comment]
Fixed in 5.3.7. Thank you
