### ISSUE TITLE
[CR] Too large loading indicator in recover from log file screen

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [lyskouski/app-finance#471]
**Describe the bug**
Too large loading indicator in recover from log file screen

**To Reproduce**
1. Go to Settings -> Recovery -> From Transactions Log file
2. See error

**Expected behavior**
Small icon in center

**Screenshots**
![image](https://github.com/lyskouski/app-finance/assets/45625440/ef0723f8-695a-4146-86f5-6e1b87b0d281)

**Desktop (please complete the following information):**
 - OS: Fedora 39, Linux 6.6.14, Flatpak 1.15.6
 - Version 5.3.5
 - Build 1554

**Additional context**

**Comment by lyskouski** [comment]
Fixed, will be a part of the nearest release.
