### ISSUE TITLE
web install doc ?

### ISSUE THREAD

**Issue by ouafnico** [lyskouski/app-finance#517]
Hi,

I'm trying to test this app, seems promising, on self-hosted web server.

Tried to use the tar.gz for web, but seems to miss a lot of files ; do you have any documentation?

Thanks

**Comment by lyskouski** [comment]
Hello @ouafnico,

Yes, you're right, base url is the only set that is needed to be changed. If it would be needed any assistance, just let me know.

**Comment by ouafnico** [comment]
That's ok, but I will create an issue, got some errors for importing ofx
