### ISSUE TITLE
[BF] Totals recalculation after a currency rate change

### ISSUE THREAD

**Issue by lyskouski** [lyskouski/app-finance#531]
Original error: https://github.com/lyskouski/app-finance/issues/529

Steps to reproduce:
- Set amount 2000
- Set 0 exchange rate
- Save bill
- Edit bill and update exchange rate to 0.00098

AR: zero state for totals
ER: reflects the edit action

![image](https://github.com/user-attachments/assets/5c377368-bbc2-4ea1-a4cb-8a04f70b64ed)

**Comment by Igortorrente** [comment]
Now it's working! Thanks @lyskouski !
