### ISSUE TITLE
[CR] App returns to Home instead of previous screen

### ISSUE THREAD

**Issue by Igortorrente** [lyskouski/app-finance#532]
**Describe the bug**
After adding/editing/deleting a income/transfers/expenses the app goes always to the home page instead of the previous page.
This make the experience of using the app more clunky and doesn't reflect the experience common on android apps.

**To Reproduce**
1. Go to Bills
2. Click on '+'
3. Add a expense 
4. The leave you on the Home

**Expected behavior**
For this example I would expect to be in the Bills section. But the same behavior happens on Budgets and Accounts.

**Desktop (please complete the following information):**
 - OS: Flatpak app
 - Version 6.0.2 1758

**Additional context**
This also happens on android.

Aside from these minor issues, great app!

**Comment by Igortorrente** [comment]
I was trying to edit several bills of a credit card and every time that I edited one, I have to go all the way back instead of returning to the bills list and edit another bill. 

I think the behavior like I described have a better balance. Because If you want to edit e single bill and go back to the home, I can click the 'Home' in the hamburger menu, or just click go 'return back' several time (which is very quick thing to do). 

I'm not trying to claim that I have the best solution, it is just a suggestion.

**Comment by lyskouski** [comment]
@Igortorrente, your proposal is perfectly fine, thanks for expressing it.

**Comment by lyskouski** [comment]
Hello @Igortorrente,
That change will be a part of the next release (6.0.3), thanks for making it better.

**Comment by Igortorrente** [comment]
Thank you for you effort!
