### ISSUE TITLE
[BF] [Linux] Exchange inconsistency

### ISSUE THREAD

**Issue by lyskouski** [lyskouski/app-finance#534]
Original issue #529.

Demo case: https://github.com/lyskouski/app-finance/issues/529#issuecomment-2535992964

Exchange summary do not reflect to the rate properly

**Comment by Igortorrente** [comment]
From #529
> If you don't mind, @Igortorrente, I'll detouch that video into a separate thread - #534 ... by now, cannot reproduce on Windows, Android, and Web versions. Might be relevant to Linux (Flatpak) package

I will try on android to see if I can reproduce on it

**Comment by lyskouski** [comment]
Hello @Igortorrente ,
Please, try 6.0.4 release

**Comment by Igortorrente** [comment]
This version fixed the issue here! Thanks @lyskouski !!!

**Comment by lyskouski** [comment]
Thanks @Igortorrente for your help in making the app better.
